### ISSUE TITLE
Skeleton theme download fails if installed to non-empty directory

### ISSUE THREAD

**Issue by jaimz22** [mothership-ec/mothership-install#5]
I run the installer, answer all the questions correctly.

The issue begins at the database migration step. 

```

Installing database tables, this might take a while
PHP Fatal error:  Class 'App' not found in /var/www/vertigolabs.org/mothership/bootstrap.php on line 5
PHP Stack trace:
PHP   1. {main}() /var/www/mothership/vendor/mothership-ec/cog/bin/cog-console:0
PHP   2. require_once() /var/www/mothership/vendor/mothership-ec/cog/bin/cog-console:19
PHP Fatal error:  Class 'App' not found in /var/www/mothership/bootstrap.php on line 5
PHP Stack trace:
PHP   1. {main}() /var/www/mothership/vendor/mothership-ec/cog/bin/cog-console:0
PHP   2. require_once() /var/www/mothership/vendor/mothership-ec/cog/bin/cog-console:19
Copying assets into project, this might take a while
PHP Fatal error:  Class 'App' not found in /var/www/mothership/bootstrap.php on line 5
PHP Stack trace:
PHP   1. {main}() /var/www/mothership/vendor/mothership-ec/cog/bin/cog-console:0
PHP   2. require_once() /var/www/mothership/vendor/mothership-ec/cog/bin/cog-console:19
PHP Fatal error:  Class 'App' not found in /var/www/mothership/bootstrap.php on line 5
PHP Stack trace:
PHP   1. {main}() /var/www/mothership/vendor/mothership-ec/cog/bin/cog-console:0
PHP   2. require_once() /var/www/mothership/vendor/mothership-ec/cog/bin/cog-console:19
PHP Fatal error:  Class 'App' not found in /var/www/mothership/bootstrap.php on line 5
PHP Stack trace:
PHP   1. {main}() /var/www/mothership/vendor/mothership-ec/cog/bin/cog-console:0
PHP   2. require_once() /var/www/mothership/vendor/mothership-ec/cog/bin/cog-console:19
Initialisation complete! Navigate to `[your URL]/admin` in your browser to start adding content
```

It never asks me for my name or anything like the readme suggests that it should. as well as it never writes anything to my database.

Also, when the installer asks for "Table Name" is that suppose to be "Schema Name"?

**Comment by jaimz22** [comment]
here is the complete console output (including my input, which i've masked) for running:

php mothership.phar ecommerce install -debug

http://pastebin.com/mQD45N8R

**Comment by thomasjthomasj** [comment]
Hi @jaimz22 

Thanks a lot for trying out Mothership, and welcome to the community :)

This issue was caused by Git failing to download the skeleton theme, as the directory it was installed in was not empty. I'm guessing the issue was that the `mothership.phar` file was present in the directory that you were trying to install the application into.

I raised an issue (https://github.com/mothership-ec/mothership-install/issues/4) about the fact that the installer does not stop running if there is an error, and will update the readme to make this clear. In time it would probably be an idea to change the way the installer handles the Skeleton theme, to use Composer's `create-project` command, as suggested in the Reddit announcement thread.

If you delete the contents of the directory, including any hidden files, and run the installer from a difference directory, it *should* work.

You are correct about the config name. nice catch, I have just opened a PR for this which should hopefully be QA'd tomorrow https://github.com/mothership-ec/cog/pull/420

**Comment by jaimz22** [comment]
So you're suggesting I move the installer and specify the path in the install command?

**Comment by jaimz22** [comment]
I saw your PR. maybe you should include the info in the installer that this won't create the schema, rather the schema should exist before the installation.

OR... make the installer create the schema.

**Comment by thomasjthomasj** [comment]
Good thinking. We considered making the installer create the database, and honestly will probably go that direction, but at first we weren't sure if it was wise to give the installer that kind of power.

You need to specify either the path to the installer, or the path to install into, I suppose. When I've been using it I've generally left the installer in my sites folder, and then been running it from an empty directory, for example if I am in the directory I want to install into I would run `php ../mothership.phar`

**Comment by kuiche** [comment]
When running the installer, the default directory is '.'. This means that specifying the path is mandatory! We should either make --path required or make the installer create a 'mothership' directory.
